    version: '3.8'

    services:
    web:
        image: nginx:alpine
        ports:
        - "8000:8000"
        volumes:
        - .:/var/www/html
        - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
        - php
        healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost/health"]
        interval: 30s
        timeout: 5s
        retries: 3

    php:
        build:
        context: './vendor/laravel/sail/runtimes/8.4'
        dockerfile: Dockerfile
        args:
            WWWGROUP: '${WWWGROUP}'
        image: 'sail-8.4/app'
        environment:
        WWWUSER: '${WWWUSER}'
        LARAVEL_SAIL: 1
        volumes:
        - '.:/var/www/html'
        healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost/health"]
        interval: 30s
        timeout: 5s
        retries: 3

    mysql:
        image: 'mysql/mysql-server:8.0'
        environment:
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        MYSQL_DATABASE: '${DB_DATABASE}'
        MYSQL_USER: '${DB_USERNAME}'
        MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
        - 'mysql-data:/var/lib/mysql'
        healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
        retries: 3
        timeout: 5s

    redis:
        image: 'redis:alpine'
        volumes:
        - 'redis-data:/data'
        healthcheck:
        test: ["CMD", "redis-cli", "ping"]
        retries: 3
        timeout: 5s

    volumes:
    mysql-data:
    redis-data:

    networks:
    default:
        name: sail
        driver: bridge