services:
  - type: web
    name: laravel-app
    runtime: docker
    dockerfilePath: ./Dockerfile
    startCommand: php artisan serve --host=0.0.0.0 --port=8000
    healthCheckPath: /health
    port: 8000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_HOST
        value: mysql
      - key: DB_PORT
        value: 3306
      - key: CACHE_DRIVER
        value: redis
      - key: SESSION_DRIVER
        value: redis
      - key: QUEUE_CONNECTION
        value: redis

  - type: mysql
    name: mysql
    runtime: docker
    dockerfilePath: ./mysql.Dockerfile # or remove if using Render's built-in DB
    startCommand: docker-entrypoint.sh mysqld
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        generateValue: true
      - key: MYSQL_DATABASE
        value: laravel
      - key: MYSQL_USER
        value: laravel
      - key: MYSQL_PASSWORD
        generateValue: true

  - type: redis
    name: redis
    runtime: docker
    dockerfilePath: ./redis.Dockerfile # or remove if using built-in Redis
    startCommand: redis-server
