services:
  - type: web
    name: laravel-app
    runtime: docker
    dockerfilePath: ./Dockerfile
    startCommand: php artisan serve --host=0.0.0.0 --port=8000
    healthCheckPath: /
    plan: free
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://your-app-name.onrender.com  # Update this after deploying
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: db4free.net  # Using external MySQL as you mentioned
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: your_db_name
      - key: DB_USERNAME
        value: your_db_user
      - key: DB_PASSWORD
        value: your_db_password
      - key: CACHE_DRIVER
        value: redis
      - key: SESSION_DRIVER
        value: redis
      - key: QUEUE_CONNECTION
        value: redis
      - key: REDIS_HOST
        value: redis
      - key: REDIS_PORT
        value: 6379

  - type: redis
    name: redis
    plan: free
